### ISSUE TITLE
[BUG] Sub-roles are created undefined

### ISSUE THREAD

**Issue by mwang2000** [nwplus/Factotum#240]
**Describe the bug**
After you click on the console of a Cave to create a new sub-role and enter the name you want it to have, it creates the role with the name "undefined".

**To Reproduce**
Steps to reproduce the behavior on Discord:
1. Run a Cave (bug was found in mentor cave with the !start-mentor-cave command)
2. Click emoji to add sub-role
3. Enter any sub-role name when prompted that is not "undefined"

**Expected behavior**
A sub-role is created with the name you entered

**Discord Platform**
Desktop app

**Comment by JPGarCar** [comment]
@meleongg how you doing with this? If you are busy I can tackle this issue today!

**Comment by meleongg** [comment]
@JPGarCar I think I got stuck on this one. It would be great if you could help me out!
